# Module: PowerShell Profile
Write-Host "  --- PowerShell Profile ---" -ForegroundColor Cyan

$profileDir = Split-Path $PROFILE -Parent
if (-not (Test-Path $profileDir)) { New-Item -ItemType Directory -Path $profileDir -Force | Out-Null }

if (Test-Path $PROFILE) {
    $backup = "$PROFILE.backup.$(Get-Date -Format 'yyyyMMdd')"
    Copy-Item $PROFILE $backup -Force
    Write-Host "  Existing profile backed up" -ForegroundColor DarkGray
}

@'
# PowerShell Profile -- auto-generated by windows-setup

# ========== STARTUP DIRECTORY ==========
Set-Location $env:USERPROFILE

# ========== MODERN CLI ALIASES ==========

# eza (beautiful ls with icons)
function List-Pretty { eza --icons --group-directories-first @args }
function List-Long { eza --icons --long --group-directories-first --git @args }
function List-Tree { eza --icons --tree --level=2 --group-directories-first @args }
Set-Alias -Name ls -Value List-Pretty -Option AllScope -Force
Set-Alias -Name ll -Value List-Long
Set-Alias -Name lt -Value List-Tree

# bat (cat with syntax highlighting)
function Read-Pretty { bat --style=auto @args }
Set-Alias -Name cat -Value Read-Pretty -Option AllScope -Force

# Common shortcuts
Set-Alias -Name which -Value Get-Command
Set-Alias -Name lg -Value lazygit
Set-Alias -Name vim -Value nvim
Set-Alias -Name vi -Value nvim

# Git shortcuts
function Git-Status { git status }
function Git-LogShort { git log --oneline -20 }
Set-Alias -Name gs -Value Git-Status
Set-Alias -Name glog -Value Git-LogShort

# Quick edit and reload profile
function Edit-Profile { notepad $PROFILE }
function Reload-Profile { . $PROFILE; Write-Host "Profile reloaded" -ForegroundColor Green }
Set-Alias -Name ep -Value Edit-Profile
Set-Alias -Name reload -Value Reload-Profile

# ========== CLAUDE CODE ==========
function Copy-McpConfig {
    $src = "$env:USERPROFILE\.claude\mcp.json"
    if (Test-Path $src) {
        Copy-Item $src -Destination ".mcp.json" -Force
        Write-Host "MCP config copied from $src" -ForegroundColor Green
    } else {
        Write-Host "MCP config not found at $src" -ForegroundColor Red
    }
}
Set-Alias -Name mcp-link -Value Copy-McpConfig

# ========== FZF (Catppuccin Mocha colors) ==========
$env:FZF_DEFAULT_OPTS = "--height 40% --layout=reverse --border --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8,fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc,marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

# ========== PATH (GnuWin32 for yazi file detection) ==========
$env:PATH = "C:\Program Files (x86)\GnuWin32\bin;$env:PATH"

# ========== OH MY POSH ==========
$poshTheme = if ($env:POSH_THEMES_PATH) {
    "$env:POSH_THEMES_PATH\catppuccin_mocha.omp.json"
} else {
    $appxPath = (Get-AppxPackage -Name 'ohmyposh.cli' -ErrorAction SilentlyContinue | Select-Object -First 1).InstallLocation
    if ($appxPath) { Join-Path $appxPath 'themes\catppuccin_mocha.omp.json' }
}
if ($poshTheme -and (Test-Path $poshTheme)) {
    oh-my-posh init pwsh --config $poshTheme | Invoke-Expression
} else {
    Write-Host "Oh My Posh theme not found" -ForegroundColor Yellow
}

# ========== ZOXIDE (smart cd) ==========
Invoke-Expression (& { (zoxide init powershell | Out-String) })

# ========== HISTORY SEARCH ==========
Set-PSReadLineKeyHandler -Key PageUp -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key PageDown -Function HistorySearchForward

# ========== STARTUP MESSAGE ==========
Write-Host "Terminal ready." -ForegroundColor DarkGray
'@ | Set-Content -Path $PROFILE -Encoding UTF8

Write-Host "  Profile created at $PROFILE" -ForegroundColor Green
