@echo off
echo.
echo  --- PowerShell Profile ---
echo.

set "PROFILE_DIR=%USERPROFILE%\Documents\PowerShell"
if not exist "%PROFILE_DIR%" mkdir "%PROFILE_DIR%"

set "PROFILE_FILE=%PROFILE_DIR%\Microsoft.PowerShell_profile.ps1"

if exist "%PROFILE_FILE%" (
    copy "%PROFILE_FILE%" "%PROFILE_FILE%.backup.%date:~-4,4%%date:~-7,2%%date:~-10,2%" >nul
    echo Existing profile backed up.
)

(
echo # PowerShell Profile — auto-generated by windows-setup
echo.
echo # ========== STARTUP DIRECTORY ==========
echo Set-Location $env:USERPROFILE
echo.
echo # ========== MODERN CLI ALIASES ==========
echo.
echo # eza ^(beautiful ls with icons^)
echo function List-Pretty { eza --icons --group-directories-first @args }
echo function List-Long { eza --icons --long --group-directories-first --git @args }
echo function List-Tree { eza --icons --tree --level=2 --group-directories-first @args }
echo Set-Alias -Name ls -Value List-Pretty -Option AllScope -Force
echo Set-Alias -Name ll -Value List-Long
echo Set-Alias -Name lt -Value List-Tree
echo.
echo # bat ^(cat with syntax highlighting^)
echo function Read-Pretty { bat --style=auto @args }
echo Set-Alias -Name cat -Value Read-Pretty -Option AllScope -Force
echo.
echo # Common shortcuts
echo Set-Alias -Name which -Value Get-Command
echo Set-Alias -Name lg -Value lazygit
echo Set-Alias -Name vim -Value nvim
echo Set-Alias -Name vi -Value nvim
echo.
echo # Git shortcuts
echo function Git-Status { git status }
echo function Git-LogShort { git log --oneline -20 }
echo Set-Alias -Name gs -Value Git-Status
echo Set-Alias -Name glog -Value Git-LogShort
echo.
echo # Quick edit and reload profile
echo function Edit-Profile { notepad $PROFILE }
echo function Reload-Profile { . $PROFILE; Write-Host "Profile reloaded" -ForegroundColor Green }
echo Set-Alias -Name ep -Value Edit-Profile
echo Set-Alias -Name reload -Value Reload-Profile
echo.
echo # ========== CLAUDE CODE ==========
echo # Copy global MCP config to current project
echo function Copy-McpConfig {
echo     $src = "$env:USERPROFILE\.claude\mcp.json"
echo     if ^(Test-Path $src^) {
echo         Copy-Item $src -Destination ".mcp.json" -Force
echo         Write-Host "MCP config copied from $src" -ForegroundColor Green
echo     } else {
echo         Write-Host "MCP config not found at $src" -ForegroundColor Red
echo     }
echo }
echo Set-Alias -Name mcp-link -Value Copy-McpConfig
echo.
echo # ========== FZF ^(Catppuccin Mocha colors^) ==========
echo $env:FZF_DEFAULT_OPTS = "--height 40%% --layout=reverse --border --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8,fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc,marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
echo.
echo # ========== PATH ^(GnuWin32 for yazi file detection^) ==========
echo $env:PATH = "C:\Program Files (x86)\GnuWin32\bin;$env:PATH"
echo.
echo # ========== OH MY POSH ==========
echo $poshTheme = if ^($env:POSH_THEMES_PATH^) {
echo     "$env:POSH_THEMES_PATH\catppuccin_mocha.omp.json"
echo } else {
echo     $appxPath = ^(Get-AppxPackage -Name 'ohmyposh.cli' -ErrorAction SilentlyContinue ^| Select-Object -First 1^).InstallLocation
echo     if ^($appxPath^) { Join-Path $appxPath 'themes\catppuccin_mocha.omp.json' }
echo }
echo if ^($poshTheme -and ^(Test-Path $poshTheme^)^) {
echo     oh-my-posh init pwsh --config $poshTheme ^| Invoke-Expression
echo } else {
echo     Write-Host "Oh My Posh theme not found" -ForegroundColor Yellow
echo }
echo.
echo # ========== ZOXIDE ^(smart cd^) ==========
echo Invoke-Expression ^(^& { ^(zoxide init powershell ^| Out-String^) }^)
echo.
echo # ========== HISTORY SEARCH ==========
echo Set-PSReadLineKeyHandler -Key PageUp -Function HistorySearchBackward
echo Set-PSReadLineKeyHandler -Key PageDown -Function HistorySearchForward
echo.
echo # ========== STARTUP MESSAGE ==========
echo Write-Host "Terminal ready." -ForegroundColor DarkGray
) > "%PROFILE_FILE%"

echo PowerShell profile created at %PROFILE_FILE%
